# This is a basic workflow to help you get started with Actions

name: stepone

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  randomfirst:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_status.outputs.result }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: set_status
        run: echo "message=This is the message from the input!!!" >> $GITHUB_OUTPUT

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: MESSAGE || Checkout code
      #  uses: actions/checkout@v4

      - name: MESSAGE || Run a multi-line script
        run: echo "Output was ${{ steps.set_output.outputs.message }}"

  randomsecond:
    needs: randomfirst
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: MESSAGE || Echoing from the second job 2
        run: echo Hello, world!
      
      - name: MESSAGE || Run a multi-line script
        run: echo "Output was ${{ steps.set_output.outputs.message }}"


  randomthird:
    needs: [randomfirst, randomsecond]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: MESSAGE || Echoing from the third job 3
        run: echo Hello, world!

  randomfourth:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: MESSAGE || Echoing from the third job 3
        run: echo Hello, world00000000000000000