# This is a basic workflow to help you get started with Actions

name: stepone

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  randomfirst:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or any version you need

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: pip install -r libs/requirements.txt

      - name: Get installed packages
        run: pip freeze


  randomsecond:
    needs: randomfirst
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: Run your script or tests
        run: python core/transform.py



  randomthird:
    needs: [randomfirst, randomsecond]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: MESSAGE || Echoing from the third job 3
        run: echo Hello, world!

  randomfourth:
    needs: [randomsecond]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    steps:
      - name: MESSAGE || Echoing from the third job 3
        run: echo Hello, world000000000000000001